### ISSUE TITLE
I get an error: missing ) after argument list

### ISSUE THREAD

**Issue by jmdavid** [Collaborne/wct-none#4]
When I launch, I get this error:

```
C:\Program Files\nodejs\node.exe c:\code\polymerapp\node_modules\.bin\wct -p --skip-plugin local --plugin none --webserver-port 2000 --expanded --simpleOutput c:/code/polymerapp/test
Debugger listening on ws://127.0.0.1:51860/3c787cbb-0951-4ecf-9e96-a94ec0ac4ccc
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
c:\code\polymerapp\node_modules\.bin\wct:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Process exited with code 1
```

**Comment by ankon** [comment]
It looks like you're on Windows, and the command referenced in the error is clearly a command for a Unix/Linux shell. 

This is not a problem of this package, or of web-component-tester, but rather in how you need to invoke scripts coming from packages in Windows. Looking through [this answer on StackOverflow](https://stackoverflow.com/a/10398567/196315) and the referenced [cmd-shim package](https://github.com/npm/cmd-shim) you likely want to invoke wct as:

```cmd
c:\code\polymerapp\node_modules\.bin\wct -p --skip-plugin local --plugin none --webserver-port 2000 --expanded --simpleOutput c:/code/polymerapp/test
```
(i.e. without explicitly prefixing things with `node.exe`)
